// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { ResourceTagArgs } from "./resourceTag";
export type ResourceTag = import("./resourceTag").ResourceTag;
export const ResourceTag: typeof import("./resourceTag").ResourceTag = null as any;
utilities.lazyLoad(exports, ["ResourceTag"], () => require("./resourceTag"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "awstags:aws:ResourceTag":
                return new ResourceTag(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("awstags", "aws", _module)
