# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import errno
from setuptools import setup, find_packages
from setuptools.command.install import install
from subprocess import check_call


VERSION = "0.0.0"
def readme():
    try:
        with open('README.md', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        return "awstags Pulumi Package - Development Version"


setup(name='pulumi_awstags',
      python_requires='>=3.7',
      version=VERSION,
      description="The AWS tags provider enables you to manage tags on already deployed or imported AWS resources.",
      long_description=readme(),
      long_description_content_type='text/markdown',
      keywords='pulumi awstags kind/native',
      url='https://github.com/nitrictech/pulumi-awstags',
      project_urls={
          'Repository': 'https://github.com/nitrictech/pulumi-awstags'
      },
      license='MIT',
      packages=find_packages(),
      package_data={
          'pulumi_awstags': [
              'py.typed',
              'pulumi-plugin.json',
          ]
      },
      install_requires=[
          'parver>=0.2.1',
          'pulumi',
          'semver>=2.8.1'
      ],
      zip_safe=False)
