# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .random import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "awstags",
  "mod": "index",
  "fqn": "pulumi_awstags",
  "classes": {
   "awstags:index:Random": "Random"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "awstags",
  "token": "pulumi:providers:awstags",
  "fqn": "pulumi_awstags",
  "class": "Provider"
 }
]
"""
)
