// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Awstags.Aws.Inputs
{

    public sealed class TagArgs : global::Pulumi.ResourceArgs
    {
        public TagArgs()
        {
        }
        public static new TagArgs Empty => new TagArgs();
    }
}
